name: gitartwork from a contribution graph
on: 
  push:
  schedule:
    - cron: '* */24 * * *'

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Nityom
          outputs: |
            dist/github-snake.svg
