name: gitartwork from a contribution graph
on: 
  push:
  schedule:
    - cron: '* */24 * * *'

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Nityom
          outputs: |
            dist/github-snake.svg
      - name: Create dist folder
        run: mkdir -p dist
      - name: Move generated SVG to dist
        run: mv github-snake.svg dist/
      - name: Commit files
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-snake.svg
          git commit -m "Add latest github-snake.svg"
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
